### ISSUE TITLE
scGate() fails 

### ISSUE THREAD

**Issue by kthorner** [carmonalab/scGate#3]
Hi, I'm really glad to find a package with this kind of functionality, and have been following the documentation, but cannot get it to work. Running scGate on an integrated Seurat object (if relevant) and the following occurs regardless of what I set as the signature:

For when assay is integrated:

Running scGate on level 1...
Error: Cannot add a different number of cells than already present

For when assay is RNA:

Running scGate on level 1...
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be positive
In addition: Warning messages:
1: In eval(predvars, data, env) : NaNs produced
2: In hvf.info$variance.expected[not.const] <- 10^fit$fitted :
  number of items to replace is not a multiple of replacement length

Thanks in advance.

**Comment by mass-a** [comment]
Hello!
would you be able to share a reproducible example, i.e. a small subset of your Seurat object and the commands you used? That would help us reproduce your error and troubleshoot.

**Comment by kthorner** [comment]
Thank you for your response!

File: https://www.dropbox.com/s/l0xg7yhcje2akhj/seurat_object.rds?dl=0
`library(scGate)
my_scGate_model <- gating_model(name = "Macrophage", signature = c("CD45","CD11b","F4-80"))
DefaultAssay(seurat.object) <- "RNA"
seurat.object <- scGate(data = seurat.object, model = my_scGate_model)`

**Comment by mass-a** [comment]
Thanks,
I see that your dataset measures 20 proteins per cell, is this CyTOF data?

scGate was mostly developed for scRNA-seq (thousand of measured genes), so it makes some assumptions that are not optimal for low-dimensional data like yours. For instance your example breaks because the programs tries to make dimensionality reduction with more dimensions that actual number of proteins in the panel. 

I have now made a quick fix for this issue in the package, if you want to reinstall and give it another try. You may also have to adjust the `pos.thr` parameter in scGate, as your score distribution is quite different from what could be expected in sparse scRNA-seq; e.g. for your macrophage signature:
```
my_scGate_model <- gating_model(name = "Macrophage", signature = c("CD45","CD11b","F4-80"))
seurat.object <- scGate(data = seurat.object, model = my_scGate_model, assay="RNA", pos.thr=0.9)
hist(seurat.object$Macrophage_UCell)
```
<img width="963" alt="Screenshot 2022-01-21 at 11 41 32" src="https://user-images.githubusercontent.com/56030596/150515222-be756c6e-b6a2-4dd5-923f-9d631f6db05d.png">

**Comment by kthorner** [comment]
Thank you for going above and beyond! I should have mentioned from the start that this was a flow experiment within Seurat. I'm seeing a lot of agreement with my other annotation methods, will be exploring this in more detail.
