### ISSUE TITLE
Can I run multiple scGate models and aggregate the results for cell types of interest?

### ISSUE THREAD

**Issue by antonioggsousa** [carmonalab/scGate#7]
Hi, 

Thank you for developing and supporting **scGate**. 

I'm running scGate across a few scRNA-seq data sets. I'm interested in T and NK cells. 
Therefore I run first the `Tcell` scGate model and then `NK`. I don't know if you can run two models simultaneously. 
Then, I look into the results and there are a very few cells that are both annotated as NK and T cell. 
I was wondering if there is a change that these may represent doublets.  

Did you ever came across this issue or is not recommended to run scGate with different models and then try to aggregate the independent results?

Thank you again. 

António

**Comment by mass-a** [comment]
Hello Antonio,

yes I think it's a reasonable approach. Those double positives for NK and T cell signatures could be doublets, or perhaps NKT cells? you could for instance check whether this subset expresses more genes on average than either the NK and T subsets – that may point towards doublets rather than to a distinct subtype?

Cheers,
-m

**Comment by antonioggsousa** [comment]
Thank you Massimo for your quick reply. 

I'll follow your advice. 

Thank you for your helpful recommendations and again for developing and supporting such a useful software. 

António
