### ISSUE TITLE
Re-use existing ucell score columns in a seurat object?

### ISSUE THREAD

**Issue by bbimber** [carmonalab/scGate#8]
Hello - 

When running scGate(), the most expensive step seems to be computing the UCell score columns, once per signature. If you re-run scGate() again, even if those columns exist, they seem to be re-calculated. Would you consider an optional flag (probably defaulting to FALSE), that would make scGate re-use any UCell columns that already exist? The use case would be if we're trying to re-run and compare different gate permutations. 

I can appreciate that if there are conflicting gene signatures then re-using UCell columns could be a problem; however, if this feature was opt-in, then it would be up to the user to understand their gates and pay attention for conflicts.

**Comment by mass-a** [comment]
Hello and thanks for the suggestion!

I agree, it would very useful to give the option to re-use precalculated UCell scores, when one wants to play with parameters of scGate downstream of signature scoring. One remark though: since the time-demanding step in UCell is ranking all genes for each cell, and this has to be done only once per run, calculating one or 100 UCell scores takes essentially the same time. Therefore in practice, the re-using of scores you suggest would only be beneficial when **all** scores have already been pre-calculated. I will add this to our bucket list of updates.

Cheers,
-m
